dist: trusty
sudo: required

install:
- sudo apt-get update
- sudo apt-get install texlive texlive-latex-extra texlive-lang-english latex-xcolor pgf librsvg2-bin gnuplot graphviz python-scipy texlive-science inkscape pdftk librtlsdr-dev libusb-1.0-0-dev

script:
- make -j8
