dist: trusty

addons:
  apt:
    packages:
      - texlive
      - texlive-latex-extra
      - texlive-lang-english
      - latex-xcolor
      - pgf
      - librsvg2-bin
      - gnuplot
      - graphviz
      - python-scipy
      - texlive-science
      - inkscape
      - pdftk
      - librtlsdr-dev
      - libusb-1.0-0-dev pv

script:
- make all
